//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_Chat
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string eMail { get; set; }
        public string Password { get; set; }
        public string token { get; set; }
        public bool aktive { get; set; }
        public int RoomID { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
